Improve Vim Syntastic Plug-in use for envConf
 - Renamed files
   - .profile -> profile.sh
   - .bashrc -> bashrc.bash
   - .kshrc -> kshrc.ksh
   - .envrc -> envrc.ksh
   - .env_init -> env_init.ksh
   - .bash_logout -> bash_logout.bash
   - .inputrc -> inputrc
 - installHome installs these into ~/
   - with proper dot-file names
   - strips out the #! line
   - strips out # shellcheck lines

diff --git a/envConf/installHome b/envConf/installHome
--- a/envConf/installHome
+++ b/envConf/installHome
@@ -1,4 +1,5 @@
 #!/bin/bash
+# shellcheck shell=bash
 #
 # Install Bash and Korn Shell environments
 # as well as other config. files into home
@@ -9,16 +10,20 @@
 #    2. Unless you are me, use this as a
 #       template for your own version.
 #    3. Run from the envConf directory.
+#    4. Dot_Files get installed with their proper names
+#       by this script.  The names used here help
+#       vim plugin syntastic use shellcheck correctly
+#       when editing them.
 #
 
 DOT_FILES='
-    .bashrc
-    .bash_logout
-    .env_init
-    .envrc
-    .inputrc
-    .kshrc
-    .profile
+    bash_logout.bash
+    bashrc.bash
+    env_init.ksh
+    envrc.ksh
+    inputrc
+    kshrc.ksh
+    profile.sh
 '
 
 RM_FILES='
@@ -45,52 +50,42 @@ BIN_SCRIPTS='
 #    ~/.bash_profile  <- want bash to use ~/.profile 
 #    ~/.vimrc         <- want  vim to use ~/.vim/vmrc
 #
-for File in $DOT_FILES $RM_FILES
+for File in $DOT_FILES
 do
+    File=".${File%.*}"
     diff ~/"$File" ~/"${File}.old" 2>&- >&-  && continue
-    [[ ! -f ~/$File ]] || cp ~/"$File" ~/"${File}.old" || {
+    [[ ! -f ~/$File ]] ||
+        cp ~/"$File" ~/"${File}.old" || {
         printf 'Error: Failed to backup previous ~/%s\n' "$File" >&2
         exit 1
     }
 done
+
 for File in $RM_FILES
 do
-    [[ ! -f ~/$File ]] || rm ~/"$File" 2>- ||
+    [[ ! -f ~/$File ]] || cp ~/"$File" ~/"${File}.old" || {
+        printf 'Error: Failed to make backup copy of ~/%s,\n' "$File" >&2
+        printf '       which was slated for removal.\n' >&2
+        exit 1
+    }
+    [[ ! -f ~/$File ]] || rm ~/"$File" 2>&- ||
         printf 'Warning: Failed to remove old ~/%s\n' "$File" >&2
 done
 
 ## Install home directory dot-files
 for File in $DOT_FILES
 do
-    cp "$File" ~ ||
-        printf 'Warning: Failed to install ~/%s\n' "$File" >&2
-    chmod u=rw,g=r,o= ~/"$File" || {
+    sed -n '4,$p' "${File}" > ~/".${File%.*}" ||
+        printf 'Warning: Failed to install ~/%s\n' ".${File%.*}" >&2
+    chmod u=rw,g=r,o= ~/".${File%.*}" || {
         printf 'Warning: Failed to set permissions' >&2
-        printf ' on ~/%s to 640\n' ~/"$File"        >&2
+        printf ' on ~/%s to 640\n' ".${File%.*}"  >&2
     }
 done
 
 ## Make sure ~/catch is there for the toSystem() shell function
 [[ -d ~/catch ]] || mkdir ~/catch ||
     printf 'Warning: Failed to create ~/catch, do so manually' >&2
-
-## Install vimrc
-[[ -d ~/.vim ]] || mkdir ~/.vim || {
-    printf 'Error: Failed to create ~/.vim,'     >&2
-    printf ' punting on installing ~/.vim/vimrc' >&2
-    exit 1
-}
-
-[[ ! -f ~/.vim/vimrc ]] || mv ~/.vim/vimrc ~/.vim/vimrc.old || {
-    printf 'Error: Failed backing up old ~/.vim/vimrc' >&2
-    exit 1
-}
-
-[[ -d ~/.vim ]] && cp ./.vim/vimrc ~/.vim ||
-    printf 'Warning: Failed to install ~/.vim/vimrc' >&2
-
-[[ -f ~/.vim/vimrc ]] && chmod u=rw,g=r,o= ~/.vim/vimrc ||
-    printf 'Warning: Failed to set permissions on ~/vim/vimrc to 640' >&2 
 
 ## Create ~/bin directory if necessary
 [[ -d ~/bin ]] || mkdir ~/bin || {
@@ -110,3 +105,22 @@ do
         printf ' on ~/bin/%s to 750\n' "$File"      >&2
     }
 done
+
+## Install vimrc
+[[ -d ~/.vim ]] || mkdir ~/.vim || {
+    printf 'Error: Failed to create ~/.vim,'     >&2
+    printf ' punting on installing ~/.vim/vimrc' >&2
+    exit 1
+}
+
+[[ ! -f ~/.vim/vimrc ]] || mv ~/.vim/vimrc ~/.vim/vimrc.old || {
+    printf 'Error: Failed backing up old ~/.vim/vimrc' >&2
+    exit 1
+}
+
+[[ -d ~/.vim ]] && cp ./vim/vimrc ~/.vim ||
+    printf 'Warning: Failed to install ~/.vim/vimrc' >&2
+
+[[ -f ~/.vim/vimrc ]] && chmod u=rw,g=r,o= ~/.vim/vimrc ||
+    printf 'Warning: Failed to set permissions on ~/vim/vimrc to 640' >&2 
+
