Neovim init.vim improvements
 - backported to vimrc
 - simplified booststrapPlug -> bsPlug
   - only using plugins with neovim

diff --git a/dotfiles/installDotfiles b/dotfiles/installDotfiles
--- a/dotfiles/installDotfiles
+++ b/dotfiles/installDotfiles
@@ -29,10 +29,11 @@ RM_FILES='
    .bash_profile
    .dashrc
    .ashrc
+   .local/bin/bootstrapPlug
 '
 
 BIN_SCRIPTS='
-   bootstrapPlug
+   bsPlug
    buArch
    digpath.bash
    digpath.sh
@@ -48,7 +49,7 @@ backup_file () {
 
    buFile="$1"
    Remove="$2"
- 
+
    diff "$buFile" "${buFile}.old" >/dev/null 2>&1 ||
        [ ! -f "$buFile" ] ||
        cp "$buFile" "${buFile}.old" || {
@@ -61,7 +62,7 @@ backup_file () {
           fi
           return 1
        }
- 
+
    [ -z "$Remove" ] ||
        [ ! -f "$buFile" ] ||
        rm "$buFile" 2>&- || {
@@ -69,7 +70,7 @@ backup_file () {
           printf "Error: Failed to remove file '%s'\\n" "$buFile" >&2
           return 1
        }
- 
+
    return 0
 }
 
@@ -79,7 +80,7 @@ install_vi_config () {
    vi_name="$1"
    vi_dir="$2"
    vi_file_name=$3
-   vi_conf_src="$vi_name/$vi_file_name"
+   vi_conf_src="$vi_file_name"
    vi_conf="$vi_dir/$vi_file_name"
 
    [ -d "$vi_dir" ] || mkdir -p "$vi_dir" || {
@@ -88,10 +89,10 @@ install_vi_config () {
       printf "punting on installing '%s' config files\\n" "$vi_name" >&2
       return 1
    }
-   
+
    # Backup previous version
    backup_file "$vi_conf" || return 1
-   
+
    # Install file
    if cp "$vi_conf_src" "$vi_dir"
    then
@@ -102,16 +103,16 @@ install_vi_config () {
    else
       printf "Warning: Failed to install '%s'\\n" "$vi_conf" >&2
    fi
- 
+
    # Set aside ~/.vimrc if configuring vim
    [ "$vi_name" != vim ] || backup_file ~/.vimrc Remove || {
        printf '\n'
        printf "Warning: Failed to move aside '~/.vimrc'\\n" >&2
        printf "         This file will supercede '%s'!\\n" "$vi_conf" >&2
-   }    
- 
+   }
+
    return 0
-}  
+}
 
 
 ## Process args - determine if user wishes Vim and/or Neovim configured
@@ -157,7 +158,7 @@ do
         ;;
     *)  printf '\n' >&2
         printf "Error: Invalid option '%s'\\n" "$1" >&2
-        printf "       Run './installHome -h' for help\\n" >&2 
+        printf "       Run './installHome -h' for help\\n" >&2
         exit 2
         ;;
   esac
@@ -175,7 +176,7 @@ done
 }
 chmod u=rwx,g=rx,o= ~/.local/bin || {
    printf '\n'
-   printf "Warning: Failed to set permissions on '~/.local/bin' to 750\n" >&2 
+   printf "Warning: Failed to set permissions on '~/.local/bin' to 750\n" >&2
 }
 
 # Create ~/catch for the toSystem () family of shell functions
@@ -198,7 +199,7 @@ done
 for File in $DOT_FILES
 do
     backup_file  ~/".${File%.*}" || exit 1
- 
+
     # Strip out syntastic info and install into $HOME
     sed -n '4,$p' "${File}" > ~/".${File%.*}" || {
        printf "Error: Failed while installing '~/%s'\\n" ".${File%.*}" >&2
@@ -236,5 +237,5 @@ XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
     [ ! -x /usr/bin/xset ] || [ ! -x /usr/bin/xrdb ] ||
     diff ~/.Xresources ~/.Xresources.old >/dev/null 2>&1 ||
     ! xset q >/dev/null 2>&1 || xrdb -merge ~/.Xresources ||
-    printf "Warning: 'xrdb ~/.Xresources' command failed\\n" 
+    printf "Warning: 'xrdb ~/.Xresources' command failed\\n"
 
