Updated envConf/bin scripts
 - pathtrim bow a POSIX shell scriot
 - minor tweaks for others

diff --git a/envConf/bin/monitor b/envConf/bin/monitor
--- a/envConf/bin/monitor
+++ b/envConf/bin/monitor
@@ -1,20 +1,28 @@
 #!/usr/bin/env bash
-[[ -d ~/monitor ]] || mkdir ~/monitor
-cd ~/monitor
-cnt=1
-> hold2
-while ((1))
+[[ -d ~/monitor ]] || mkdir ~/monitor || {
+    printf 'monitor: Error - Faild to create ~/monitor dirctory\n'
+    exit 1
+} 
+
+cd ~/monitor || {
+    printf 'monitor: Error - Faild to cd to ~/monitor dirctory\n'
+    exit 1
+} 
+
+true > hold2
+
+((cnt=1))
+while true
 do
     who > hold1
-    diff hold1 hold2 >/dev/null 2>&1
-    if (( $? == 0 ))
+    if diff hold1 hold2 >/dev/null 2>&1
     then
-        sleep 60
+        :
     else
-        cp hold1 change_${cnt}
+        cp hold1 change_$((cnt))
         cp hold1 hold2
+        printf '%d\n' $((cnt))
         (( cnt++ ))
-        echo $cnt
-        sleep 60
     fi
+    sleep 60
 done
