Updated env/
 - Reducing .vim/vimrc relative to .config/nvim/init.vim
   - not using plugins for vim anymore
   - .vim/vimrc present in case nvim not available
 - Fixed small bugs installHome and buArch
 - Fixed typo in comment in ~/.Xresources

diff --git a/env/bin/buArch b/env/bin/buArch
--- a/env/bin/buArch
+++ b/env/bin/buArch
@@ -75,27 +75,27 @@ fi
 printf 'INFO: Now backup to external HD\n' >&2
 
 if printf -- '--exclude=%s/\n' "${ExcludeDirs[@]}" | {
-     mapfile -t ExcludeDirFlags
-     printf -- '--exclude=%s\n' "${ExcludeFiles[@]}" | {
-        mapfile -t ExcludeFileFlags
-        /usr/bin/rsync -avxP --delete \
-          "${ExcludeDirFlags[@]}" \
-          "${ExcludeFileFlags[@]}" \
-          "${HOME}" \
-          "$BackupLocation/" || {
-             RSYNC_FAILURE=$?
-             printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE" >&2
-             printf 'ERROR: Failed backing up Home directory\n' >&2
-             exit 1
-          }
-     }
-  }
+   mapfile -t ExcludeDirFlags
+   printf -- '--exclude=%s\n' "${ExcludeFiles[@]}" | {
+      mapfile -t ExcludeFileFlags
+      /usr/bin/rsync -avxP --delete \
+      "${ExcludeDirFlags[@]}" \
+      "${ExcludeFileFlags[@]}" \
+      "${HOME}" \
+      "$BackupLocation/" || {
+         RSYNC_FAILURE=$?
+         printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE" >&2
+         printf 'ERROR: Failed backing up Home directory\n' >&2
+         exit 1
+      }
+   }
+}
 then
     # Success
-    printf 'INFO: Backup to external HD successful!\n' >&2
+    printf '\nINFO: Backup to external HD successful!\n' >&2
     exit 0
 else
     # Failure
-    printf 'WARNING: Problems with backup to external HD!\n' >&2
+    printf '\nWARNING: Problems with backup to external HD!\n' >&2
     exit 1
 fi
