Rewrote env/bin/buArch backup script
 - Backs up most of my home directory via rsync
   - excludes various things line ~/.cache, ~/Videos
   - excludes ~/devel since that gets backed up to GitHub
 - gauss17ArchLinuxAdmin.log updates regaurding on-going issues:
   - getting file permissions to work on external HD
   - getting Bluetooth working

diff --git a/env/bin/buArch b/env/bin/buArch
--- a/env/bin/buArch
+++ b/env/bin/buArch
@@ -8,238 +8,87 @@
 
 ## Backup configuration
 
-BackupLocation='/run/media/grs/BUSLINK/grsBackupArch'
+BackupLocation='/run/media/grs/BUSLINK/grsBackup'
 
-HomeFiles=(
-    .bashrc
-    .dashrc
-    .envrc
-    .inputrc
-    .kshrc
-    .profile
-    .shrc
+ExcludeDirs=(
+    devel
+    Videos
+    OneDrive
+    .sane
+    .cache
+    .config/evolution
+    .local/share/evolution
+    .local/share/gvfs-metadata
 )
 
-HomeDirs=(
-    bin
-    info
-    Music
-    Pictures
-    .gnupg
-    .pki
-    .ssh
-    .zoom
-)
-
-VimFile=.vim/vimrc
-
-DevelDirs=(
-    devel/local
-)
-
-ConfigDirs=(
-    .config/autostart
-    .config/dconf
-    .config/discord
-    .config/lbry
-    .config/onedrive
-    .config/zoomus.conf
-)
-
-LocalShareDirs=(
-    .local/share/keyrings
-    .local/share/lbry
-)
-
-VideoDirs=(
-    Videos/Family
-    Videos/MartialArts
+ExcludeFiles=(
+    .dropbox-dist
 )
 
 ## Run script from home directory
-cd ~ || { printf 'Error: Cannot cd to home dir\n'; exit 1; }
+
+cd ~ || { printf 'Error: Cannot cd to home dir\n'; exit 1; } >&2
 
 ## First, backup Evolution Mail App to filesystem before ext HD
-printf 'INFO: Archiving Evolution\n'
+
+printf 'INFO: Archiving Evolution\n' >&2
 
 EvolutionBackupUtil=/usr/lib/evolution/evolution-backup
 EvolutionBackupFile=~/info/EvolutionBackup/evolution_backup.tar.gz
 
 if [[ ! -x $EvolutionBackupUtil ]]; then
-    printf 'WARNING: Evolution backup utility, %s,\n' $EvolutionBackupUtil
-    printf '         either not found or not executable.\n'
+    printf 'WARNING: Evolution backup utility, %s,\n' $EvolutionBackupUtil >&2
+    printf '         either not found or not executable.\n' >&2
 elif [[ ! -d ${EvolutionBackupFile%/*} ]]; then
     if mkdir -p "${EvolutionBackupFile%/*}" 
     then
         $EvolutionBackupUtil --backup "$EvolutionBackupFile" ||
-            printf 'WARNING: Evolution backup failed\n'
+            printf 'WARNING: Evolution backup failed\n' >&2
     else
-        printf 'WARNING: Cannot create %s' "${EvolutionBackupFile%/*}"
-        printf ' directory\n'
+        printf 'WARNING: Cannot create %s' "${EvolutionBackupFile%/*}" >&2
+        printf ' directory\n' >&2
     fi
 else
     $EvolutionBackupUtil --backup "$EvolutionBackupFile" ||
-        printf 'WARNING: Evolution backup failed\n'
+        printf 'WARNING: Evolution backup failed\n' >&2
 fi
 
-## Prepare backup location on external HD
-printf '\nINFO: Preparing external HD for backup\n'
+## Check backup location on external HD
 
-# Make sure backup location available
+printf '\nINFO: Checking external HD backup location\n' >&2
+
 if [[ ! -d $BackupLocation ]]
 then
-    printf 'Error: backup location, %s, not found\n' "$BackupLocation"
+    printf 'Error: backup location, %s, not found\n' "$BackupLocation" >&2
     exit 1
 fi
 
-# Make sure ,vim is setup on external HD
-if [[ ! -d $BackupLocation/.vim ]]
-then
-    mkdir "$BackupLocation/.vim" || {
-            printf 'Error: failed creating %s\n' "$BackupLocation/.vim"
-            exit 1
-    }
-fi
-
-# Make sure devel is setup on external HD
-if [[ ! -d $BackupLocation/devel ]]
-then
-    mkdir "$BackupLocation/devel" || {
-            printf 'Error: failed creating %s\n' "$BackupLocation/devel"
-            exit 1
-    }
-fi
-
-# Make sure .config is setup on external HD
-if [[ ! -d $BackupLocation/.config ]]
-then
-    mkdir "$BackupLocation/.config" || {
-            printf 'Error: failed creating %s\n' "$BackupLocation/.config"
-            exit 1
-    }
-fi
-
-# Make sure .local/share is setup on external HD
-if [[ ! -d $BackupLocation/.local/share ]]
-then
-    mkdir -p "$BackupLocation/.local/share" || {
-            printf 'Error: failed creating %s\n' "$BackupLocation/.local/share" 
-            exit 1
-    }
-fi
-
-# Make sure Videos is setup on external HD
-if [[ ! -d $BackupLocation/Videos ]]
-then
-    mkdir "$BackupLocation/Videos" || {
-            printf 'Error: failed creating %s\n' "$BackupLocation/Videos"
-            exit 1
-    }
-fi
-
 ## Backup to External HD
-printf 'INFO: Now backup to external HD\n'
 
-# Backup $HomeFiles
-printf 'INFO: Selectively backing up environment configuration files\n'
-/usr/bin/rsync -ai --no-perms --delete \
-    "${HomeFiles[@]}" \
-    "$BackupLocation" || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${HomeFiles[@]}"
-        printf 'WARNING: Not backed up %s\n' "${HomeDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VimFile}"
-        printf 'WARNING: Not backed up %s\n' "${DevelDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${ConfigDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${LocalShareDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VideoDirs[@]}"
-        exit 1
+printf 'INFO: Now backup to external HD\n' >&2
+
+printf -- '--exclude=%s/\n' "${ExcludeDirs[@]}" | {
+   mapfile -t ExcludeDirFlags
+   printf -- '--exclude=%s\n' "${ExcludeFiles[@]}" | {
+      mapfile -t ExcludeFileFlags
+      /usr/bin/rsync -avxP --delete \
+        "${ExcludeDirFlags[@]}" \
+        "${ExcludeFileFlags[@]}" \
+        "${HOME}" \
+        "$BackupLocation/" || {
+           RSYNC_FAILURE=$?
+           printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE" >&2
+           printf 'ERROR: Failed backing up Home directory\n' >&2
+           exit 1
+        }
+   }
 }
 
-
-# Backup $HomeDirs
-printf 'INFO: Backing up %s\n' "${HomeDirs[*]}"
-/usr/bin/rsync -ai --no-perms --delete \
-    "${HomeDirs[@]}" \
-    "$BackupLocation" || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${HomeDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VimFile}"
-        printf 'WARNING: Not backed up %s\n' "${DevelDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${ConfigDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${LocalShareDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VideoDirs[@]}"
-        exit 1
-}
-
-# Backup $VimFile
-printf 'INFO: Backing up ~/.vim\n'
-/usr/bin/rsync -ai --no-perms --delete \
-    "${VimFile}" \
-    "$BackupLocation/.vim" || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${VimFile}"
-        printf 'WARNING: Not backed up %s\n' "${DevelDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${ConfigDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${LocalShareDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VideoDirs[@]}"
-        exit 1
-}
-
-# Backup $DevelDirs
-printf 'INFO: Selectively backing up ~/devel\n'
-/usr/bin/rsync -ai --no-perms --delete \
-    "${DevelDirs[@]}" \
-    "$BackupLocation/devel" || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${DevelDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${ConfigDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${LocalShareDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VideoDirs[@]}"
-        exit 1
-}
-
-# Backup $ConfigDirs
-printf 'INFO: Selectively backing up ~/.config\n'
-/usr/bin/rsync -ai --no-perms --delete \
-    "${ConfigDirs[@]}" \
-    "$BackupLocation/.config" || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${ConfigDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${LocalShareDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VideoDirs[@]}"
-        exit 1
-}
-
-# Backup $LocalShareDirs
-printf 'INFO: Selectively backing up ~/.local/share\n'
-/usr/bin/rsync -ai --no-perms --delete --exclude=blobfiles \
-    "${LocalShareDirs[@]}" \
-    "$BackupLocation/.local/share" \
-  || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${LocalShareDirs[@]}"
-        printf 'WARNING: Not backed up %s\n' "${VideoDirs[@]}"
-        exit 1
-     }
-
-# Backup $VideoDirs
-printf 'INFO: Selectively backing up ~/Videos\n'
-/usr/bin/rsync -ai --no-perms --delete \
-    "${VideoDirs[@]}" \
-    "$BackupLocation/Videos" \
-  || {
-        RSYNC_FAILURE=$?
-        printf 'ERROR: rsync failure with error %s\n' "$RSYNC_FAILURE"
-        printf 'ERROR: Failed backing up %s\n' "${VideoDirs[@]}"
-        exit 1
-     }
-
-printf 'INFO: Backup to Ext HD Successful\n'
-exit 0
+if (( $? == 0 ))
+then
+    printf 'INFO: Backup to external HD successful!\n' >&2
+    exit 0
+else
+    printf 'WARNING: Problems with backup to external HD!\n' >&2
+    exit 1
+fi
