env/installHome now installs bin/* -> ./local/bin
 - adjusted config files and scripts accordingly
 - fixed wrong repo name in some files
 - unrelated notes/gnome3Conf.md update

diff --git a/env/installHome b/env/installHome
--- a/env/installHome
+++ b/env/installHome
@@ -50,22 +50,22 @@ backup_file () {
    diff "$buFile" "${buFile}.old" >/dev/null 2>&1 ||
        [ ! -f "$buFile" ] ||
        cp "$buFile" "${buFile}.old" || {
-           printf '\n'
-           printf "Error: Failed to make backup copy of '%s'" "$buFile" >&2
-           if [ -z "$Remove" ]; then
-               printf '\n'
-           else
-               printf ',\n       which was slated for removal.\n' >&2
-           fi
-           return 1
+          printf '\n'
+          printf "Error: Failed to make backup copy of '%s'" "$buFile" >&2
+          if [ -z "$Remove" ]; then
+              printf '\n'
+          else
+              printf ',\n       which was slated for removal.\n' >&2
+          fi
+          return 1
        }
  
    [ -z "$Remove" ] ||
        [ ! -f "$buFile" ] ||
        rm "$buFile" 2>&- || {
-           printf '\n'
-           printf "Error: Failed to remove file '%s'\\n" "$buFile" >&2
-           return 1
+          printf '\n'
+          printf "Error: Failed to remove file '%s'\\n" "$buFile" >&2
+          return 1
        }
  
    return 0
@@ -81,10 +81,10 @@ install_vi_config () {
    vi_conf="$vi_dir/$vi_file_name"
 
    [ -d "$vi_dir" ] || mkdir -p "$vi_dir" || {
-        printf '\n'
-        printf "Error: Failed to create '%s' directory,\\n" "$vi_conf" >&2
-        printf "punting on installing '%s' config files\\n" "$vi_name" >&2
-        return 1
+      printf '\n'
+      printf "Error: Failed to create '%s' directory,\\n" "$vi_conf" >&2
+      printf "punting on installing '%s' config files\\n" "$vi_name" >&2
+      return 1
    }
    
    # Backup previous version
@@ -93,19 +93,19 @@ install_vi_config () {
    # Install file
    if cp "$vi_conf_src" "$vi_dir"
    then
-        chmod u=rw,g=r,o= "$vi_conf" || {
-            printf '\n'
-            printf "Warning: Failed to set permissions on '%s' to 640\\n" "$vi_conf" >&2
-        }
+      chmod u=rw,g=r,o= "$vi_conf" || {
+          printf '\n'
+          printf "Warning: Failed to set permissions on '%s' to 640\\n" "$vi_conf" >&2
+      }
    else
-        printf "Warning: Failed to install '%s'\\n" "$vi_conf" >&2
+      printf "Warning: Failed to install '%s'\\n" "$vi_conf" >&2
    fi
  
    # Set aside ~/.vimrc if configuring vim
    [ "$vi_name" != vim ] || backup_file ~/.vimrc Remove || {
-        printf '\n'
-        printf "Warning: Failed to move aside '~/.vimrc'\\n" >&2
-        printf "         This file will supercede '%s'!\\n" "$vi_conf" >&2
+       printf '\n'
+       printf "Warning: Failed to move aside '~/.vimrc'\\n" >&2
+       printf "         This file will supercede '%s'!\\n" "$vi_conf" >&2
    }    
  
    return 0
@@ -164,21 +164,21 @@ done
 
 ## Create $HOME directory structure if needed
 
-# Create ~/bin directory if necessary
-[ -d ~/bin ] || mkdir ~/bin || {
-    printf '\n'
-    printf 'Error: Failed to create ~/bin\n' >&2
-    exit 1
+# Create ~/.local/bin directory if necessary
+[ -d ~/.local/bin ] || mkdir ~/.local/bin || {
+   printf '\n'
+   printf 'Error: Failed to create ~/.local/bin\n' >&2
+   exit 1
 }
-chmod u=rwx,g=rx,o= ~/bin || {
-    printf '\n'
-    printf "Warning: Failed to set permissions on '~/bin' to 750\n" >&2 
+chmod u=rwx,g=rx,o= ~/.local/bin || {
+   printf '\n'
+   printf "Warning: Failed to set permissions on '~/.local/bin' to 750\n" >&2 
 }
 
 # Create ~/catch for the toSystem () family of shell functions
 [ -d ~/catch ] || mkdir ~/catch || {
-    printf '\n'
-    printf "Warning: Failed to create '~/catch', do so manually\\n" >&2
+   printf '\n'
+   printf "Warning: Failed to create '~/catch', do so manually\\n" >&2
 }
 
 
@@ -198,23 +198,24 @@ do
  
     # Strip out syntastic info and install into $HOME
     sed -n '4,$p' "${File}" > ~/".${File%.*}" || {
-         printf "Error: Failed while installing '~/%s'\\n" ".${File%.*}" >&2
-         exit 1
+       printf "Error: Failed while installing '~/%s'\\n" ".${File%.*}" >&2
+       exit 1
     }
     # Set permissions
     chmod u=rw,g=r,o= ~/".${File%.*}" || {
-         printf 'Warning: Failed to set permissions' >&2
-         printf ' on ~/%s to 640\n' ".${File%.*}"  >&2
+       printf 'Warning: Failed to set permissions' >&2
+       printf ' on ~/%s to 640\n' ".${File%.*}"  >&2
     }
 done
 
-# Install ~/bin scripts
+# Install ~/.local/bin scripts
 for File in $BIN_SCRIPTS
 do
-    cp bin/"$File" ~/bin/ || printf 'Warning: Failed to install ~/bin/%s\n' "$File" >&2
-    chmod u=rwx,g=rx,o= ~/bin/"${File}" || {
-         printf 'Warning: Failed to set permissions' >&2
-         printf ' on ~/bin/%s to 750\n' "${File}" >&2
+    cp bin/"$File" ~/.local/bin/ ||
+       printf 'Warning: Failed to install ~/.local//bin/%s\n' "$File" >&2
+    chmod u=rwx,g=rx,o= ~/.local/bin/"${File}" || {
+       printf 'Warning: Failed to set permissions' >&2
+       printf ' on ~/.local/bin/%s to 750\n' "${File}" >&2
     }
 done
 
